# Generated by Django 4.2.4 on 2023-12-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_crypto_cryptobalance_cryptovalue_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
    ]
