# Generated by Django 4.2.4 on 2023-12-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cryptobalance_balance_alter_cryptovalue_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balnce',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=20),
            preserve_default=False,
        ),
    ]
