# Generated by Django 4.2.4 on 2023-12-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_balnce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balnce',
        ),
    ]
